# version: '3.8'

# services:
#   frontend:
#     build: ./frontend
#     ports:
#       - "8888:80"
#     restart: always

#   backend:
#     build: ./backend
#     ports:
#       - "3000:3000"
#     restart: always
#     environment:
#       - NODE_ENV=production
version: '3.8'

services:
  frontend:
    image: baontd2103/todo-frontend:latest
    container_name: todo-frontend
    expose:
      - "80"
    restart: always

  backend:
    image: baontd2103/todo-backend:latest
    container_name: todo-backend
    expose:
      - "3000"
    restart: always
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"  # Chỉ expose duy nhất cổng 80 ra ngoài
    volumes:
      - ./nginx/default.conf/nginx-todo.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
