version: '2.2'

services:
  frontend:
    build: ./frontend
    ports:
      - "8888:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
