version: '2.2'

services:
  frontend:
    build: ./frontend
    ports:
      - "8888:80"
    restart: always

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
