version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8888:80"
    restart: always

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
