version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8888:8888"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-todo.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    container_name: nginx


# version: '3.8'

# services:
#   frontend:
#     image: baontd2103/todo-frontend:latest
#     container_name: todo-frontend
#     expose:
#       - "80"
#     restart: always

#   backend:
#     image: baontd2103/todo-backend:latest
#     container_name: todo-backend
#     expose:
#       - "3000"
#     restart: always
#     environment:
#       - NODE_ENV=production

#   nginx:
#     image: nginx:alpine
#     container_name: reverse-proxy
#     ports:
#       - "80:80"  # Chỉ expose duy nhất cổng 80 ra ngoài
#     volumes:
#       - ./nginx/nginx-todo.conf:/etc/nginx/conf.d/default.conf:ro
#     depends_on:
#       - frontend
#       - backend
#     restart: always

# version: '3.8'

# services:
#   frontend:
#     image: baontd2103/todo-frontend:latest
#     container_name: todo-frontend
#     expose:
#       - "80"
#     restart: always
#     networks:
#       - todo-network

#   backend:
#     image: baontd2103/todo-backend:latest
#     container_name: todo-backend
#     expose:
#       - "3000"
#     restart: always
#     environment:
#       - NODE_ENV=production
#     networks:
#       - todo-network

#   nginx:
#     image: nginx:alpine
#     container_name: reverse-proxy
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/nginx-todo.conf:/etc/nginx/conf.d/default.conf:ro
#     depends_on:
#       - frontend
#       - backend
#     restart: always
#     networks:
#       - todo-network

# networks:
#   todo-network:
#     driver: bridge
